### ISSUE TITLE
Find a better video component

### ISSUE THREAD

**Issue by Shadyzpop** [SocialXNetwork/socialx_react_native#111]
inconsistent video component, and doesnt play well with the current one

**Comment by ChristBKK** [comment]
any update here @alexcroitoru95  ?

**Comment by alexcroitoru95** [comment]
Yes, [](https://github.com/react-native-community/react-native-video). Implementing it now :)

**Comment by ChristBKK** [comment]
@alexcroitoru95  what is the status here?

**Comment by alexcroitoru95** [comment]
It works ok on iOS, instead it had to be fixed on Android. Me and @Shadyzpop managed to make some native module modifications, but it's still in process.
