### ISSUE TITLE
Search of the app crashes the app

### ISSUE THREAD

**Issue by marcelinhio** [SocialXNetwork/socialx_react_native#116]
**Describe the bug**
I was searching for jake but it crashed

**To Reproduce**
Search for jake

**Expected behavior**
I thought i could add some one from search as a friend

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 Iphone X

**Additional context**
Bugsnag report see slack

**Comment by ChristBKK** [comment]
yes same for me, report via bugsnag

**Comment by alexsirbu04** [comment]
I cannot reproduce this. Search works, both on sim and on my device. Maybe it's related to the networking issues? @Shadyzpop
