### ISSUE TITLE
once friend accepted - there is still undo action

### ISSUE THREAD

**Issue by marcelinhio** [SocialXNetwork/socialx_react_native#117]
**Describe the bug**
I added @hahaha as friend, he accepted (notification screenshot) then i went to his profile and saw the action undo. Which should not be.

**To Reproduce**
1. add a friend
2. wait until he confirms
3. see notification
4. from notification tab go to his profile
5. see undo button

**Expected behavior**
I would like to see the button (friends) instead of undo.

**Screenshots**
see screenshots

**Smartphone (please complete the following information):**
Iphone X

**Additional context**
As discussed in Slack
![img_9907](https://user-images.githubusercontent.com/10127805/48772662-071e2880-ed00-11e8-9d6b-046db03484de.PNG)
![img_9906](https://user-images.githubusercontent.com/10127805/48772663-07b6bf00-ed00-11e8-8ca1-d37d017c67da.PNG)

**Comment by alexsirbu04** [comment]
This a backend issue. For some reason, accepting a friend requests throws a "failed to create friend" error, but the user that sent the request receives the accepted notification. @Shadyzpop

**Comment by Shadyzpop** [comment]
fixed with the new version
