### ISSUE TITLE
Extend Redux to support optimistic data updates

### ISSUE THREAD

**Issue by alexsirbu04** [SocialXNetwork/socialx_react_native#121]
A little background first. Right now, the way we are doing updates is by dispatching a thunk, waiting for the response and then updating the UI. This creates a really bad UX. The correct way of doing this is by dispatching an action first to update the state in the store, ensuring instant feedback for the user, then dispatching the thunk in the background and reverting the update if an error comes back.
This way we can also normalize the state in the store and do the mapping to the desired shape in the reducers, improving app performance.

**Comment by Shadyzpop** [comment]
fixed with the new version
