### ISSUE TITLE
Can't accept Friend Request from Jakeee

### ISSUE THREAD

**Issue by ChristBKK** [SocialXNetwork/socialx_react_native#123]
**Describe the bug**
Can't accept Friend Request from Jakeee

**To Reproduce**
1. Go to Notifications
2. Click on Accept Friend Request
3. Nothing happens

**Expected behavior**
Accept friend request

**Screenshots**
![46517002_2225794707741512_6413075193056460800_n](https://user-images.githubusercontent.com/12375330/48967731-b6684180-f017-11e8-9276-25e93c629426.jpg)

**Smartphone (please complete the following information):**
Vivo V9
Android

**Comment by ChristBKK** [comment]
still with 0.26

**Comment by Shadyzpop** [comment]
this happens because the user `jaakee` is already friends with your current profile, so the request fails, its a side effect from switching versions from 0.25/x-0.26
