### ISSUE TITLE
comments are not visible after posting

### ISSUE THREAD

**Issue by marcelinhio** [SocialXNetwork/socialx_react_native#126]
**Describe the bug**
post a comment but the comment is not directly visible (usually it was visible after waiting for 2-3 seconds)

**To Reproduce**
1. post comment
2. wait 5 seconds
3. comment not visible
4. switch to other page in the app or reopen the app again
5. see the comment only then.

**Expected behavior**
I would expect that the comment shows up DIRECTLY after posting

**Screenshots**
no screenshot

**Smartphone (please complete the following information):**
Iphone X

**Additional context**
Jake mentioned i should assign it directly to you Alex

**Comment by alexsirbu04** [comment]
This is a drawback of our current Redux structure. I'll try to fix it asap.

**Comment by ChristBKK** [comment]
+1 for this one

**Comment by alexsirbu04** [comment]
This is fixed on my branch as my commit referenced it.

**Comment by Shadyzpop** [comment]
fixed with the new version
