### ISSUE TITLE
fixed the problem with refreshing both the user feeds

### ISSUE THREAD

**Issue by Shadyzpop** [SocialXNetwork/socialx_react_native#135]
the refresh functionality was not working before, now its reseting the feed store and refetches the posts on the specific feed accordingly

problems are:
* upon refreshing, the feed goes to the initial state then after the posts are loaded it reflects
* if there is no posts on a feed, the user does have to ability to refresh that feed and is stuck on the initial state until restarted

**Comment by Shadyzpop** [comment]
related 8703dddb0a627db7c871f297e839fdb20bdd63e6

**Comment by ChristBKK** [comment]
yep I have that

**Comment by Shadyzpop** [comment]
fixed with the new version
