### ISSUE TITLE
Load more Posts doesn't work or is super slow

### ISSUE THREAD

**Issue by ChristBKK** [SocialXNetwork/socialx_react_native#136]
**Describe the bug**
Load more Posts doesn't work or is super slow

**To Reproduce**
Scroll down on the Feed and try to load more posts

**Screenshots**
see bottom of the screenshot attached 

**Smartphone (please complete the following information):**
Android
Vivo V9

![47442163_1226356770846979_7015126318287159296_n](https://user-images.githubusercontent.com/12375330/49498291-1f17af80-f89d-11e8-9ead-2bfe649bc8bc.jpg)

**Comment by Shadyzpop** [comment]
fixed with the new version
