### ISSUE TITLE
Feed Loading not resolving

### ISSUE THREAD

**Issue by ChristBKK** [SocialXNetwork/socialx_react_native#140]
**Describe the bug**
Feed Loading not resolving

**To Reproduce**
1. Start App
2. Wait 

**Smartphone (please complete the following information):**
Android
Vivo V9 

![47498945_556159871519846_5892935579561099264_n](https://user-images.githubusercontent.com/12375330/49631216-bb6bbe80-fa23-11e8-9bd1-80b4e18229bb.jpg)

**Comment by Shadyzpop** [comment]
fixed on 3a898e9e3f03647d913a36f6dec0d12ee434d7d8
