### ISSUE TITLE
search crashes

### ISSUE THREAD

**Issue by marcelinhio** [SocialXNetwork/socialx_react_native#143]
**Describe the bug**
serach crashed when searching for philip

**To Reproduce**
1. search
2. type philip
3. app crashes

**Expected behavior**
I would like to see everyone with name philip

**Screenshots**
see video https://drive.google.com/open?id=1Twu6_QNQQwyULlGMIyI7dWmcQHDukdnU

**Smartphone (please complete the following information):**
Iphone X
Latest iOS

**Comment by ChristBKK** [comment]
https://app.bugsnag.com/socialx/socialx/errors/5bd4aa5a68b58400193e38a4?filters[event.since][0]=30d&filters[error.status][0]=open
