### ISSUE TITLE
UI is slow to respond

### ISSUE THREAD

**Issue by 1000goalgaming** [SocialXNetwork/socialx_react_native#148]
**Describe the bug**
I've just got on the app a minute ago and I'm already noticing the UI is very slow - every time I press a button it takes several seconds or more to respond back, and I can't do anything else in that time. Is it the mining? Is there a separate reason (e.g. blockchain taking its sweet time)? I think the UI should be more optimized in the coming months.

**To Reproduce**
1. Use the app for a period of time.
2. Push buttons.
3. Go to new pages.
4. Like photos.

**Smartphone (please complete the following information):**
 - Device: LG
 - OS: Android

**Comment by ChristBKK** [comment]
No bug, feature request
