### ISSUE TITLE
Add friend buttons don't do anything

### ISSUE THREAD

**Issue by 1000goalgaming** [SocialXNetwork/socialx_react_native#149]
**Describe the bug**
Add friend buttons don't do anything

**To Reproduce**
1. Go to search
2. Try to add a friend

**Expected behavior**
I'd expect the pink button to change and the request to go through.

**Smartphone (please complete the following information):**
 - Device: LG
 - OS: Android

**Additional context**
![capture _2018-12-14-06-52-58 1](https://user-images.githubusercontent.com/31747246/50004562-26118280-ff6d-11e8-81df-355d74d8cd65.png)

**Comment by alexcroitoru95** [comment]
@1000goalgaming Please provide Android OS Version

**Comment by 1000goalgaming** [comment]
Android 7.0, LG K20V

**Comment by alexcroitoru95** [comment]
@1000goalgaming Can you please try again and let us know if this works for you? Thx :)

**Comment by 1000goalgaming** [comment]
It only works a small fraction of the time, most of the time it will keep to its normal state and say "Could not add the user."

**Comment by alexcroitoru95** [comment]
@1000goalgaming We will have a new release soon. Please wait until it's available and then test it again. Thx 👍

**Comment by ChristBKK** [comment]
@1000goalgaming  please check with the new version, thanks

**Comment by 1000goalgaming** [comment]
Can't get to that screen as of now, will let you know when it happens

**Comment by Shadyzpop** [comment]
a new version will be released to the store tonight, would be appreciated if u could try it by then, thank you
