### ISSUE TITLE
Wallet screen is just a placeholder

### ISSUE THREAD

**Issue by 1000goalgaming** [SocialXNetwork/socialx_react_native#150]
**Describe the bug**
The wallet is just a placeholder, you may want to fix that in the future ^^

**To Reproduce**
1. Go to your profile
2. Go to the three-dot action menu
3. Click on 'Wallet'

**Expected behavior**
My wallet should actually be shown

**Screenshots**
![capture _2018-12-14-07-03-37 1](https://user-images.githubusercontent.com/31747246/50005010-750be780-ff6e-11e8-9d88-638447ffd5a0.png)

**Smartphone (please complete the following information):**
 - Device: LG
 - OS: Android

**Comment by ChristBKK** [comment]
No bug, feature request
