### ISSUE TITLE
uploading a video on android doesnt work

### ISSUE THREAD

**Issue by Shadyzpop** [SocialXNetwork/socialx_react_native#155]
the condition to check if the item is a video is failing thus passing an undefined to the path on the uploader

**Comment by Shadyzpop** [comment]
after it finishes uploading the video, it crashes with setState on unmounted component

**Comment by alexcroitoru95** [comment]
The video uploading works on iPhone 7 OS 12.1.1 (16C50). Maybe the problem is related when uploading an image and a video on a single post.

**Comment by alexcroitoru95** [comment]
Working on Nexus 5X Android 9 API 28 (Video Uploading, Video FullScreen and Video Thumbnail are all working)

**Comment by Shadyzpop** [comment]
@alexcroitoru95 ill leave this to you, if u can please check it once more on Nexus 6 Api 28 and if its okay, feel free to close this issue 😝

**Comment by alexcroitoru95** [comment]
@Shadyzpop cool

**Comment by alexcroitoru95** [comment]
Works on Nexus 5 Android 8.1 API 26, Nexus 6 Android 9 API 28
