### ISSUE TITLE
SocialX app crashes for no reason

### ISSUE THREAD

**Issue by 1000goalgaming** [SocialXNetwork/socialx_react_native#156]
**Describe the bug**
The app crashes at random points for no reason, just like last big version (back in May.) Sometimes it'll just happen when going on a page (like the feed or profile), and sometimes it'll happen when attempting to post (which is more prevalent). 
**To Reproduce**
1. Use the app, click around, try to post
2. It crashes

**Smartphone (please complete the following information):**
 - Device: LG K20V (VS501)
 - OS: Android 7.0
 - Software Version: VS5011AA

![capture _2018-12-15-10-54-40 1](https://user-images.githubusercontent.com/31747246/50048380-0161fb80-0090-11e9-9c4f-bfbab9367a7f.png)

**Comment by alexsirbu04** [comment]
Can you pinpoint some actions that cause these crashes? Or are they completely random?

**Comment by 1000goalgaming** [comment]
@alexsirbu04 A lot of randomness involved, but it usually happens after switching pages (e.g. to view your Feed/Profile/etc), or while posting.

**Comment by ChristBKK** [comment]
@1000goalgaming  are the crashes still appearing?

**Comment by 1000goalgaming** [comment]
Doesn't seem to be crashing on me anymore, but I still get the "Oops, error occured" bug that doesn't let me use the app..

**Comment by ChristBKK** [comment]
Thanks @1000goalgaming  let's test it with the next version coming soon. I keep the issue open till then.

**Comment by 1000goalgaming** [comment]
Nevermind, it just crashed

**Comment by ChristBKK** [comment]
@1000goalgaming  did you install the new version and test again please? :)

**Comment by 1000goalgaming** [comment]
The new version is installed, seems to get all the way to 100% with the progress bar and then instantly afterwards, it crashes.
