### ISSUE TITLE
Feed is empty after loading the app

### ISSUE THREAD

**Issue by 1000goalgaming** [SocialXNetwork/socialx_react_native#166]
**Describe the bug**
When I launch the app, it goes through the normal progress bar... it goes to 100% and then I am confronted with this screen. Most of the time this error occurs, though by random chance every once in a while it'll go away

**To Reproduce**
1. Launch the app
2. Be unlucky

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: LG K20
 - OS: Android 7.0 Nougat
![capture _2018-12-22-11-53-54 1](https://user-images.githubusercontent.com/31747246/50377922-c447bd00-05eb-11e9-9a8a-509448a0d72b.png)

**Comment by ChristBKK** [comment]
@1000goalgaming  please check if the problem still occurs or if that is fixed now.
Thanks for your help!

**Comment by 1000goalgaming** [comment]
Still getting this occasionally. Seems to be okay rn tho
