### ISSUE TITLE
Unfortunately, SocialX has stopped

### ISSUE THREAD

**Issue by Bakhid** [SocialXNetwork/socialx_react_native#168]
I have just downloaded it via PS and when I launched, it says "Unfortunately, SocialX has stopped".

Android version: 4.4.4 KTU84P
Model number: MI 4LTE-CU
MIUI version: MIUI 7.0 | Stable 7.00.55.00 (KXDMICI)

**Comment by ChristBKK** [comment]
Hey @Bakhid , thanks for opening this issue. Unfortunately we can't support very old Android versions like Android Kit-Kat. Please try to install it with a more recent phone btw. Android version.
Thanks
