### ISSUE TITLE
Could not create your account

### ISSUE THREAD

**Issue by slaven944** [SocialXNetwork/socialx_react_native#170]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - OS: [e.g. iOS8.1 , Android]

**Additional Information (App related):**
 - Username: [e.g. mrBeans]
 - Network type: [e.g. Wifi]
 - Version [e.g. 3.5]

**Additional context**

**Comment by ChristBKK** [comment]
@slaven944  can you please be more specific on your description?  What is not working? And where is it not working? Thanks :)

**Comment by alexsirbu04** [comment]
Please try again and report if it's still not working. Should be fixed.

**Comment by slaven944** [comment]
Thank) Working. Happy New Year 2019)

вс, 30 дек. 2018 г. в 19:17, Alex Sirbu <notifications@github.com>:
