### ISSUE TITLE
App crashes instantly on startup

### ISSUE THREAD

**Issue by snowmanmedia** [SocialXNetwork/socialx_react_native#171]
After installing from the link provided, when the app is opened, the app briefly opens before crashing
No SocialX logo is displayed and no part of the app opens before the app closes

Steps to reproduce the behaviour:
1. Install the app from the link provided
2. Open the app
3. App crashes

The app should open, but does not

No screenshots available due to the nature of the bug crashing the app as soon as it opens

Smartphone
 - Device: motorola XT1052
 - OS: Android 4.4.2
 - RAM: 4 GB

**Comment by alexcroitoru95** [comment]
Will do @Shadyzpop

**Comment by alexcroitoru95** [comment]
@Shadyzpop I can only test with Android 5.1 Lollipop API 22 and it works.

**Comment by ChristBKK** [comment]
@snowmanmedia  unfortunately we can't support Android versions from 2013 with SocialX. Please check if you can install the application on a more recent phone, thanks.
