### ISSUE TITLE
Could not add friend

### ISSUE THREAD

**Issue by sysulsb** [SocialXNetwork/socialx_react_native#172]
hi, when i try to add friend.it said:"Could not add the user"

Smartphone

Device: huawei Honor V10
OS: Android 8.0.0
RAM: 6 GB
![22](https://user-images.githubusercontent.com/35393878/50570742-beaf5b80-0dd1-11e9-80bf-6ef0360b1a03.jpg)

**Comment by ChristBKK** [comment]
maybe related to #149 . Thanks for reporting it, we are investigating it right now

**Comment by sysulsb** [comment]
@ChristBKK it is ok now. but the speed need to improve. it need 3-5 second to add one friend

**Comment by ChristBKK** [comment]
Thanks for your feedback @sysulsb  we ware working on it to improve the speed.
