### ISSUE TITLE
App Crashes 

### ISSUE THREAD

**Issue by ayodelehazeley** [SocialXNetwork/socialx_react_native#179]
When I try to upload a new post; the social x app crashes 
Steps to reproduce 
Open Social X App
Click to upload photo 
Select photo 
Select to post 
Crash & returns error 

iPhone 7+ iOS 12.1.2

**Comment by alexcroitoru95** [comment]
@ayodelehazeley We will test this and come back with a response. Thank you!

**Comment by Apola123** [comment]
I am getting the same error when uploading pictures.
I phone 7 
Ios 12.1.2

**Comment by Shadyzpop** [comment]
fixed in the new version
