### ISSUE TITLE
"Return button" does not work when displaying pictures in fullscreenmode

### ISSUE THREAD

**Issue by PhilipFilhol** [SocialXNetwork/socialx_react_native#181]
![socialx bug](https://user-images.githubusercontent.com/44616626/51544799-f2295700-1e60-11e9-9d80-a051156c6ab6.png)

Samsung Galaxy S9 with Android 8.0.0

**Comment by alexcroitoru95** [comment]
Hey @PhilipFilhol, we are trying right now to fix this issue. We will let you know when it is done. Thx :)

**Comment by alexcroitoru95** [comment]
This issue has been fixed and will be included in the next release :)
