### ISSUE TITLE
Issue on edit profile pic

### ISSUE THREAD

**Issue by Mar-25** [SocialXNetwork/socialx_react_native#184]
Can't put any info in bio even putting my profile pic.
Always freeze.
![screenshot_20190211-003142](https://user-images.githubusercontent.com/47502313/52536463-e82ab200-2d95-11e9-80fa-21e67a6d9e21.png)

SKK HYPER X CORE
Android version 6.0

**Comment by ChristBKK** [comment]
Discussing with @Shadyzpop
