### ISSUE TITLE
You need to reload again and again to see post.

### ISSUE THREAD

**Issue by Mar-25** [SocialXNetwork/socialx_react_native#186]
![screenshot_20190211-004913](https://user-images.githubusercontent.com/47502313/52536708-13fb6700-2d99-11e9-9f27-8091429833a1.png)

Have a hard time to see my post.

**Comment by Mar-25** [comment]
SKK HYPER X CORE
ANDROID VERSION 6.0

**Comment by ChristBKK** [comment]
thanks for reporting discussing with @Shadyzpop  how to improve that
