### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by morandi89** [SocialXNetwork/socialx_react_native#191]
I updated the application, I launch and give an error, send a report.
![screenshot_2019-03-01-21-54-17](https://user-images.githubusercontent.com/3081119/53659877-a04ccb80-3c6d-11e9-879b-6aea62315482.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [.Samsung Galaxy S4]
 - OS: [  Android  ]
 - Version [ 5.1]

**Additional Information (App related):**
 - Username: [morandi89 ]
 - Network type: [. Wifi]
 - Version [e.g. 3.5]

**Additional context**

**Comment by Apola123** [comment]
I am having the same issue. When launching the app I get the Error“Something went wrong...“
I phone 7
IOS Version 12.1.2
Network Wifi

**Comment by Shadyzpop** [comment]
Thanks for the report, ill try resolving this recurring issue within the next version
