### ISSUE TITLE
Keyboard Context prop issue

### ISSUE THREAD

**Issue by alexcroitoru95** [SocialXNetwork/socialx_react_native#90]
The prop marginBottom from KeyboardContext is not working.

For example: 
- When a user has clicked on Report a Problem and then on Subject, the keyboard pops over the modal when in fact the modal should receive marginBottom as prop.

**Comment by ChristBKK** [comment]
is this done @alexcroitoru95 ?

**Comment by alexcroitoru95** [comment]
This will be implemented with @Shadyzpop and @alexsirbu04 because it has to be refactored

**Comment by ChristBKK** [comment]
okay what is the status here? keyboard is in the way when i want to post a comment in the feed screen under a post @alexsirbu04  and @alexcroitoru95
