### ISSUE TITLE
Make Global Feed Tab Primary (show first)

### ISSUE THREAD

**Issue by ChristBKK** [SocialXNetwork/socialx_react_native#94]
Please make on the Feed Screen the Global feed primary (show first) instead of the Friends Feed.

**Comment by alexcroitoru95** [comment]
Fixed. Reviewed by @Alex and @Shadyzpop.

**Comment by alexcroitoru95** [comment]
Fixed. Reviewed by @alexsirbu04 and @Shadyzpop
