### ISSUE TITLE
Hide Message Button on Profile Page for now 

### ISSUE THREAD

**Issue by ChristBKK** [SocialXNetwork/socialx_react_native#95]
Please hide the Message Button on the Profile Page for now or make a "coming soon"

![45751592_313804399227167_6392931805028155392_n](https://user-images.githubusercontent.com/12375330/48282476-5b1d4780-e48c-11e8-8fc6-7d23fabb4725.jpg)

**Comment by alexcroitoru95** [comment]
Commented for now. Reviewed by @alexsirbu04 and @Shadyzpop .
