### ISSUE TITLE
Please change on the Share Post Screen the following

### ISSUE THREAD

**Issue by ChristBKK** [SocialXNetwork/socialx_react_native#96]
Message to  "Share"
"Type a Message" to "Write a caption"

![46047405_342670109842510_1497096295100186624_n](https://user-images.githubusercontent.com/12375330/48282522-7be59d00-e48c-11e8-9752-b3476c6a1a64.jpg)

**Comment by alexcroitoru95** [comment]
Fixed. Reviewed by @alexsirbu04 and @Shadyzpop .
